### ISSUE TITLE
Image linking will not work

### ISSUE THREAD

**Issue by Sebby-T** [algonquindesign-grads/2020#31]
Hey Thomas,

I'm currently creating the grad card for the 2020 website and I'm trying to link up the icons. I used the process shown by Patricia in Slack.

Here's the code;

<a class="grad-card text-center ib island-1-2" href="#">
  <div class="grad-img push-1-2 chop">
    <img class="img-flex" src="https://via.placeholder.com/600" alt="">
  </div>
  <div class="grad-cont text-left relative">
    <h4 class="push-0  normal">
      <span class="block mega">First Name</span>
      <span class="block kilo">Longer Last Name.</span>
    </h4>
    <div class="grad-icon pin-tr">
      <i class="icon i-32">
        <img src="{{site.imgurl}}/designers/icons.svg#face-icon" alt="">
      </i>
    </div>
  </div>
</a>

I used `<img src="{{site.imgurl}}/designers/icons.svg#face-icon" alt="">` but I get nothing.

Any ideas?

@thomasjbradley

**Comment by thomasjbradley** [comment]
Are you trying to grab an icon out of the `icons.svg` spritesheet? Because that would need `<svg><use>` to work.

**Comment by Sebby-T** [comment]
> Are you trying to grab an icon out of the `icons.svg` spritesheet? Because that would need `<svg><use>` to work.
I tried this as well and it still doesn't give me the icon. Am I using it right?
`<svg><use xlink:href="{{site.imgurl}}/designers/icons.svg#face-icon" /></svg>`

**Comment by thomasjbradley** [comment]
The `icons.svg` file isn’t in the `designers` folder, it’s right in the root:

```xml
<svg><use xlink:href="{{site.imgurl}}/icons.svg#face-icon" /></svg>
```

**Comment by Sebby-T** [comment]
Right, I fixed that but the icons still don't seem to load.

The normal `img` tag src is working just fine with images.
It doesn't seem to want to pull any icon from the `icons.svg `

**Comment by thomasjbradley** [comment]
Seems to be a cross-origin problem. I’m looking into it now.

**Comment by thomasjbradley** [comment]
SVGs are allowed in the Git repo. So just commit it in there for now. I can’t seem to readily see a solution. I think that is might “just work” when it gets deployed on the live server.

**Comment by Sebby-T** [comment]
Yeah, we've decided to add it that way. Thanks, Thomas for the help!
