### ISSUE TITLE
Teacher Card

### ISSUE THREAD

**Issue by sander-aaron** [algonquindesign-grads/2020#49]
Hey Thomas, @thomasjbradley 

I'm currently trying to get the teacher card to spit out all the info from the _teachers. I have both config files updated, and I have the card and everything else set up like how the Grad-card is. I'm not entirely sure what I'm missing to get the cards to fill out, maybe you could take a look.

I'm working in supporter-layout and the files I've been working in are supporter.html, teachers-section and teacher-card.

Thanks :)

**Comment by thomasjbradley** [comment]
Did you figure this out? It seems to be working to me. At least all the teachers are being shown. I do see a small error: you don’t need `layout: teachers` at the top of each MD because they aren’t going to become their own pages.

**Comment by sander-aaron** [comment]
I took the layout: teachers out of the mds, but this is what the card looks like:
<img width="214" alt="Screen Shot 2020-02-20 at 9 13 39 AM" src="https://user-images.githubusercontent.com/31959117/74941645-5f3f5100-53c1-11ea-81d3-b9dfd96ffc8d.png">
I'm trying to get the image/text to display but I can't figure out why they're not showing up.

**Comment by thomasjbradley** [comment]
There’s 1 typo:
In the MD, it’s named `subject`, but in the HTML it’s called as `subject_taught`

Also, I see in my MD file, the image is written just like this:
`prof_headshot: "headshot-bradley-thomas.jpg"`
And the rest of the URL is written in the HTML file. But the rest of the teachers don’t have the simplified version of the URL in their MD file.

**Comment by sander-aaron** [comment]
Thank you! I'll make the fixes and see if it works :)

**Comment by sander-aaron** [comment]
So I tested and think it's something in the config that isn't connecting the md's to the pattern because I'm still getting no data input. I switched out the URL in your md to the full version (https://grads.images.algonquindesign.ca/2020/supporters/teacher-headshots/headshot-bradley-thomas.jpg) to test and got a src(unknown).
<img width="711" alt="Screen Shot 2020-02-20 at 9 30 50 AM" src="https://user-images.githubusercontent.com/31959117/74944312-d8d83e80-53c3-11ea-922f-614e6fb31b69.png">
This is the config file:
<img width="502" alt="Screen Shot 2020-02-20 at 9 29 39 AM" src="https://user-images.githubusercontent.com/31959117/74944340-e392d380-53c3-11ea-8124-a9ce39bf5068.png">

**Comment by thomasjbradley** [comment]
I’m not sure what you’re seeing. It seems to be working as expected for me:

![Screen Shot 2020-02-20 at 11 07 58 AM](https://user-images.githubusercontent.com/105192/74954569-4e96d700-53d1-11ea-8f95-c1ddd8f01cfd.png)

**Comment by sander-aaron** [comment]
Oh weird! I'll show you it in class tomorrow!
