### ISSUE TITLE
Terminal Error

### ISSUE THREAD

**Issue by sander-aaron** [algonquindesign-grads/2020#56]
Hey, @thomasjbradley 

I was trying to open the site and ended up getting this error in my terminal. I was going to give the site one last check before we set it live. 

<img width="572" alt="Screen Shot 2020-02-28 at 2 04 32 PM" src="https://user-images.githubusercontent.com/31959117/75630045-51ee4780-5bb5-11ea-9cbe-30ed9d1f61c5.png">

**Comment by thomasjbradley** [comment]
Try running `bundle install`

**Comment by thomasjbradley** [comment]
Then try running `bundle exec jekyll serve --trace` and it’ll give you a more detailed answer.

**Comment by sander-aaron** [comment]
So I ran bundle exec jekyll serve --trace and got this
<img width="567" alt="Screen Shot 2020-03-01 at 12 14 34 PM" src="https://user-images.githubusercontent.com/31959117/75630174-40596f80-5bb6-11ea-9b8f-5a8fea665c16.png">

**Comment by thomasjbradley** [comment]
Seems to be something with downloading the Typekit fonts for the pattern library.

See where it says `CssParser::RemoteFileError:` copy that URL into your browser and see where it goes.

**Comment by sander-aaron** [comment]
It just leads me to a "this site can't be reached" page. Here's the link: https://p.typekit.net:443/p.css?s=1&k=ahq7wki&ht=tk&f=12101.12102.12103.12104.22002.22003.22004.22005&a=9119916&app=typekit&e=css

**Comment by thomasjbradley** [comment]
Hmm. Mine is just coming up as an empty CSS file, with only a comment.

**Comment by sander-aaron** [comment]
Oh, weird. What does the comment say? I'll search through the files and see if I can find it

**Comment by thomasjbradley** [comment]
Nothing. It’s completely empty. `/**/`

**Comment by thomasjbradley** [comment]
Did someone make changes to the Typekit web project recently?

**Comment by sander-aaron** [comment]
I think it might be banner.css. I just checked and the file is empty.
And no, I don't think so, I'll check the link to make sure it is correct

**Comment by sander-aaron** [comment]
Both instances of the font link were correct

**Comment by thomasjbradley** [comment]
It’s not your CSS that’s the problem. It’s Typekit.

The only thing I can think of right now is your IP is being blocked. But I don’t know why. Maybe give it an hour and try again..?

**Comment by sander-aaron** [comment]
Oh ok, I'm coming back to Ottawa tonight so I'll try when I get back.
